version: 2
jobs:
  build:

    working_directory: ~/miroassignment

    docker:
      - image: circleci/openjdk:14.0.2-buster

    steps:
      - checkout
      - restore_cache:
          key: circleci-miroassignment-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-miroassignment-{{ checksum "pom.xml" }}

      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/miroassignment-0.0.1-SNAPSHOT.jar
